[tool.poetry]
name = "chat_webSocket"
version = "1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.9"
pymongo = "^4.6.1"
passlib = "^1.7.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
